### ISSUE TITLE
Can this do memory mapped not to file (e.g. not persisted/stored to/from disk)?

### ISSUE THREAD

**Issue by LiamKarlMitchell** [ozra/mmap-io#21]
And is it cross platform?

Thanks

**Comment by ozra** [comment]
1. Yes
2. I'm a Linux-only dude, but two contributors has shaped it up for Mac and Windows too. Not to sure about the state currently though.

**Comment by ozra** [comment]
Win + Mac was added in 2015, and caught up a couple of times with breaking lib changes.
